#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
clean_arness_visuals.py

Delete ARness visual artifacts generated by previous visual_arness_trace.py runs.

Default dry-run, so it only prints what would be removed.
Use --execute to actually delete.

Targets:
  - visual/arness
  - outputs/arness/**/visual_trace
  - outputs/arness/**/visual_arness_overview
  - outputs/arness/visual_arness_overview
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path
from typing import List


def collect_targets(outputs_root: Path, visual_root: Path, extra_roots: List[Path]) -> List[Path]:
    targets: List[Path] = []

    for p in [visual_root, *extra_roots]:
        if p.exists():
            targets.append(p)

    if outputs_root.exists():
        for name in ["visual_trace", "visual_arness_overview"]:
            for p in outputs_root.rglob(name):
                if p.is_dir():
                    targets.append(p)

    # de-duplicate and avoid deleting a child if parent is already selected
    uniq = sorted(set(p.resolve() for p in targets), key=lambda x: (len(x.parts), str(x)))
    final: List[Path] = []
    for p in uniq:
        if any(str(p).startswith(str(parent) + "/") or str(p).startswith(str(parent) + "\\") for parent in final):
            continue
        final.append(p)
    return final


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outputs-root", default="outputs/arness")
    ap.add_argument("--visual-root", default="visual/arness")
    ap.add_argument("--extra-visual-roots", nargs="*", default=[], help="Optional old visual roots to delete, e.g. visual/arness_trace")
    ap.add_argument("--execute", action="store_true", help="Actually delete. Without this, only dry-run.")
    args = ap.parse_args()

    outputs_root = Path(args.outputs_root)
    visual_root = Path(args.visual_root)
    extra_roots = [Path(x) for x in args.extra_visual_roots]

    targets = collect_targets(outputs_root, visual_root, extra_roots)
    if not targets:
        print("[OK] no visual artifacts found")
        return

    print("[INFO] targets:")
    for p in targets:
        print(f"  {p}")

    if not args.execute:
        print("\n[DRY-RUN] nothing deleted. Add --execute to delete these directories.")
        return

    for p in targets:
        if p.exists():
            shutil.rmtree(p)
            print(f"[DELETED] {p}")

    print("[DONE] deleted ARness visual artifacts")


if __name__ == "__main__":
    main()
